Int resolve
tsandmann/ct-bot pull request #38
Opened 2018-04-03 18:29 UTC by Nightwalker-87

2018-04-04 16:46 UTC, Nightwalker-87 commented
Beim letzten commit könnte man nochmal schauen ob an einigen stellen auch int8_t bzw. uint8_t ausreicht... Das hab ich vergessen nachzuschauen. Es baut so aber erstmal erfolgreich.

2018-04-05 12:41 UTC, tsandmann requested changes
Ich habe mal über die meisten (nicht alle) Änderungen drübergeschaut: 
1. An den allermeisten Stellen, wo im aktuellen Code int verwendet wird, ist das absichtlich und aus einem sehr guten Grund der Fall, nämlich damit es korrekt funktioniert.
2. Dort wo mit dem Betriebssystem interagiert wird (Sockets, ioctls, Handles für Files o.ä., Baudraten) verwendet int, weil das Betriebssystem dies so vorschreibt, das darf nicht geändert werden, sonst funktioniert es nicht mehr korrekt.
3. Wo (C) Standard-Libs int zurückgeben, kann/sollte man oftmals auch damit weiterarbeiten, der Standard definiert nun mal diesen Typ dafür. Wenn man es explizit konvertiert, sollte sichergestellt sein, dass das auch genau das ist, was gewünscht ist.
4. Die Änderungen in global.h z.B. werden zum Crash unter Windows führen. 
5. Die FatFile Library ist eine externe Library, die nicht geändert werden sollte. Da das MCU-only Code ist, stört int hier auch nicht weiter.

2018-04-05 15:29 UTC, Nightwalker-87 commented
Hiermit sei dein feedback zumindest zum Großteil schon einmal berücksichtigt. Ein paar Fundstellen sind aber noch dazugekommen. Abgesehen vom behaviour neuralnet (was ich mir auch nochmal ansehen werde) wäre ich dann einmal durch den Code durch.

2018-04-06 16:23 UTC, tsandmann approved these changes

2018-04-06 16:24 UTC, merged