develop
tsandmann/ct-bot pull request #48
Opened 2019-03-20 20:48 UTC by Nightwalker-87

2019-03-23 14:06 UTC, tsandmann requested changes
Danke für die Updates :-)
Ein paar Dinge sind mir allerdings noch aufgefallen:
- in `.cproject` sind irgendwie zusätzliche Settings hereingeraten, die da für das ct-Bot Projekt nicht hingehören: `optionalBuildProperties="org.eclipse.cdt.docker.launcher.containerbuild.property.volumes=,org.eclipse.cdt.docker.launcher.containerbuild.property.selectedvolumes="`
- Die Wildcards im Makefile sind zwar auf den ersten Blick sehr praktisch, die hatten wir (vor langer Zeit) aber extra mal ausgeschlossen, weil dadurch die Reihenfolge nicht mehr dieselbe ist wie beim Eclipse-Build. Dadurch waren die Ergebnisse nicht mehr direkt vergleichbar, weshalb die Liste mit allen Dateien und einer definierten Reihenfolge entstanden ist.
- `ifeq ($(BUILD_TARGET), armv8l-linux-gnueabihf | arm-linux-gnueabihf)` im Makefile funktioniert nicht, weil beide Variante unterschiedliche Optionen brauchen. 
  - In dem Zusammenhang ist mir auch noch ein Fehler in der aktuellen Makefile-Version aufgefallen, die Optionen `mcpu`, `mtune`, `mfloar-abi` und `mfpu` werden nur in den `CFLAGS` gesetzt und nicht auch in den `CXXFLAGS` und `ASFLAGS`. Das könnte man gleich mal mit fixen, sonst funktioniert das Ergebnis eh nicht so ganz korrekt.

2019-03-23 16:19 UTC, Nightwalker-87 commented
Ok, das ist soweit nachvollziehbar.
- Die Options in .cproject hat Eclipse wohl unbemerkt ergänzt. Habe vergleichbares gerade reproduzieren können. Einstellung gesetzt, gespeichert, Einstellung wieder zurückgesetzt --> .cprojekt hat sich trotzdem verändert. Da muss ich zukünftig genauer drauf achten - das ist echt ziemlich bescheuert... 
- Das mit den Wildcard konnte ich nicht wissen; ich passe das entsprechend an und ergänze einen Kommentar mit der Info
- die Korrektur rund um das ARM-Buildtarget muss ich mir erst nochmal anschauen, den Fix zu den CXX-Flags kann ich aber schon einbauen.

2019-03-23 18:53 UTC, tsandmann commented
> * Den Fix zu den CXX- und AR-Flags für das ARM-Buildtarget ergänze ich gleich mit. Zu den -mcpu/-mtune/-mfpu Flags: Gelten die [GCC ARM-Options](https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html) nicht für arm-linux-gnueabihf? Ich hatte das zumindest so verstanden ...

Ja die Optionen schon, sie müssen für `armv8l-linux-gnueabihf` (RPi 3) und `arm-linux-gnueabihf` (RPi 2) aber auf unterschiedliche Werte gesetzt werden. So wie derzeit im Makefile.

2019-03-23 19:08 UTC, Nightwalker-87 commented
Ne, dann ist es meines Erachtens wohl auch kein Verständnisproblem:
Das war beides für RPi3 gedacht, die RPi2-Unterstützung hatte ich wie in der Commit-Message mit-aufgelistet aus dem Makefile entfernt, da du vor einiger Zeit bereits schon das entsprechende Eclipse-Build-Target und die Travis CI Testconfig entfernt hattest. Also entweder sollte man die RPi2 Unterstützung entweder insgesamt drin lassen oder ganz rausnehmen, dann aber auch alle Überreste davon. Ich hatte mich da einfach nur an diesem Commit cd85840781ff0511c1e3d2ed4d9b7bd2facea063 und zugehörigen Commits von dir orientiert...

2019-03-23 19:12 UTC, tsandmann commented
Ach so, auch okay. 
Dann sollte aber in `ifeq ($(BUILD_TARGET), armv8l-linux-gnueabihf | arm-linux-gnueabihf)` auch `arm-linux-gnueabihf` mit raus, weil das ist da falsch.

2019-03-23 19:16 UTC, Nightwalker-87 commented
ja, also zumindest wird es da aktuell standardmäßig nicht verwendet. Man könnte aber auch hergehen unter linux (was ich schon mal gemacht hatte) und die interne Toolchain `arm-linux-gnueabihf` anstelle der selbstgebauten `armv8l-linux-gnueabihf` für den RPi3-Build verwenden, wenn man die Doku entsprechend ergänzt. Das ginge dann schon. Wie wollen wir es machen?

2019-03-23 19:48 UTC, tsandmann commented
Wenn die gesetzten Optionen da dann auch passen, ja.

2019-03-23 20:11 UTC, Nightwalker-87 commented
jo, also das Debian-Paket [gcc-arm-linux-gnueabihf](https://packages.debian.org/stretch/gcc-arm-linux-gnueabihf) was auch nach Ubuntu portiert wird installiert nach `/usr/bin/arm-linux-gnueabihf-gcc` sodass _arm-linux-gnueabihf-gcc_ es automatisch via $PATH zugänglich ist. Der Name ist auch identisch, sodass hier keine weiteren Anpassungen erforderlich sind. Müsste dann nur als Alternative Toolchain in der Doku gelistet werden mit ein paar Zeilen Info dazu. Es ist wirklich sehr praktisch.

2019-03-23 20:33 UTC, tsandmann commented
Was ist ich meinte ist, ob die Optionen auch funktionieren. Es kommt darauf an, mit welchen Optionen z.B. die C-Library der Toolchain gebaut ist, die dann dazu gelinkt wird. Dass der GCC die Optionen grundsätzlich unterstützt, ist klar.

2019-03-23 22:04 UTC, Nightwalker-87 commented
ah, sry das war wirklich sehr ungünstig ausgedrückt von mir: Gemeint war, dass unter [GCC ARM-Options](https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html) steht dass `-mcpu=neon-fp-armv8`, `-mcpu=/-mtune=cortex-a53` & `-mfpu=neon-fp-armv8` gültige Optionen sind. Ich dachte ich könnte die Beschreibung etwas abkürzen und war in dem Glauben, dass trotzdem klar ist was gemeint ist.
Besteht dann trotzdem noch die Möglichkeit, dass nicht alle laut Doku möglichen Parameter für eine Option beim Kompilieren der Toolchain berücksichtigt sind? Das wäre ja für ein breit verteiltes Paket für die ARM-hf Architektur irgendwie auch seltsam. Was ich mir noch vorstellen könnte wäre, dass neuere Architekturen vllt _noch_ nicht mit an Bord sind wenn es sich nicht um die neueste Version handelt. Wo kann ich das am Besten verifizieren? Das müsste ja in irgendwelchen Readme-Dateien im Paket vermerkt sein eigentlich... Würde das schon gerne noch abschließend geklärt wissen.

2019-03-23 23:05 UTC, tsandmann commented
Die Frage ist, mit welchen Optionen sie die Libraries compiliert haben. Die müssen nicht unbedingt optimal sein, aber halt kompatibel. In der gcc-Doku steht halt nur, was der gcc kann, das ist sicherlich auch völlig korrekt so. Wird wohl am einfachsten sein, das erzeugte Programm auf einem RPi auszuprobieren, ob es funktioniert. 
Dann ist die Veroderung im Makefile aber okay so, man sollte dann nur dokumentieren, dass **immer** für die RPi 3 CPU gebaut wird (bei *arm\*-linux-gnueabihf* in `BUILD_TARGET`), unabhängig davon, wie `BUILD_TARGET` genau gesetzt ist.

2019-03-23 23:16 UTC, Nightwalker-87 commented
Also die Doku würde ich diesbezüglich ohnehin ergänzen, keine Frage. Wäre trotzdem schön hier im Detail noch abschließende Klarheit zu haben. Hier nun erstmal das Update wie besprochen:

2019-03-24 12:15 UTC, tsandmann commented
Fehlt jetzt nicht der `doc`-Ordner in der Exclude-Liste in `.cproject`?

2019-03-24 12:17 UTC, Nightwalker-87 commented
Also er zeigt mir /doc als excluded an, kann aber nochmal nachsehen zur Kontrolle.

2019-03-24 12:18 UTC, tsandmann commented
Ah sorry, falscher Alarm. Das stand vorher schon drin, darum hab ich es in der Änderungsliste nicht gefunden. Passt.

2019-03-24 12:19 UTC, tsandmann approved these changes

2019-03-24 12:41 UTC, merged

2019-03-24 12:42 UTC, tsandmann commented
Danke fürs Aufräumen / Strukturieren von Makefile und Doku 👍