Develop
tsandmann/ct-bot pull request #53
Opened 2019-04-30 11:29 UTC by Nightwalker-87

2019-04-30 11:35 UTC, Nightwalker-87 commented
Mom, da habe ich etwas übersehen; Bugfix folgt.

2019-04-30 23:00 UTC, Nightwalker-87 commented
`/home/travis/build/tsandmann/ct-bot/tests/avr8-gnu-toolchain-linux_x86_64/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld: section .bootloader loaded at [000000000000f800,000000000000fc89] overlaps section .text loaded at [0000000000000000,000000000000f995]
/home/travis/build/tsandmann/ct-bot/tests/avr8-gnu-toolchain-linux_x86_64/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld: section .data loaded at [000000000000f996,000000000000fa67] overlaps section .bootloader loaded at [000000000000f800,000000000000fc89]
collect2: error: ld returned 1 exit status
Makefile:517: recipe for target 'ct-Bot.elf' failed
make: *** [ct-Bot.elf] Error 1
TEST /home/travis/build/tsandmann/ct-bot/tests/mcu/01_all_options_mcu.h FOR MCU FAILED.`

Hier ist momentan noch nicht wirklich klar warum es jetzt zu diesem Überlauf kommt, den es vorher so nicht gab. Im Direktvergleich vorher/nachher konnte ich derzeit noch keinen Punkt entdecken, welcher hierfür verantwortlich ist. Im Testcase sollte das ja eigentlich nicht passieren - wenn der Speicher voll ist ist er nun mal voll. Die kleinere Speichergröße ist ja bekannt und wird beim Test normalerweise auch berücksichtigt. (Hatte ich zumindest so wahrgenommen). Hast du eine Idee dazu? Am Besten wäre wohl wir klären das im Chat.

Das ATmega644p-Target würde ich derzeit noch im Code behalten, weil diese etwas neuere MCU-Variante von den verfügbaren Pin-Funktionen dem 1284p deutlich näher ist. Ein 64kB-Flashspeicher ist per-se ja auch noch brauchbar, wenn auch mit Einschränkungen.

2019-05-01 14:21 UTC, tsandmann commented
Warum sollte man denn die Unterstützung für den ATmega644 entfernen? Der funktioniert doch gut und es gibt Leute, die den verwenden.

2019-06-10 21:13 UTC, tsandmann requested changes
* Die Änderungen im Makefile für das Target `program` bewirken, dass immer die Fusebits neu gesetzt werden. Das ist a) zu gefährlich und sollte nicht gemacht werden und hat b) noch den Fehler, dass gleichzeitig die Werte für "mit Bootloader" und "ohne Bootloader" gesetzt werden, das kann so nicht funktionieren.
 * Die Datei `.settings/language.settings.xml` sollte ignoriert werden (siehe README.md), weil sie automatisch generiert wird. Änderungen hier gehören nicht mit in den Commit.

2019-06-11 08:37 UTC, Nightwalker-87 commented
>     * Die Änderungen im Makefile für das Target `program` bewirken, dass immer die Fusebits neu gesetzt werden. Das ist a) zu gefährlich und sollte nicht gemacht werden und hat b) noch den Fehler, dass gleichzeitig die Werte für "mit Bootloader" und "ohne Bootloader" gesetzt werden, das kann so nicht funktionieren.

Nope, wegen der Auskommetierung von
`# AVRDUDE_WRITE_EEPROM = -U eeprom:w:$(TARGET).eep:i -v
  # AVRDUDE_WRITE_FUSE = -U lfuse:w:0xF7:m -U hfuse:w:0xD1:m -U efuse:w:0xFF:m -v`


> 
>     * Die Datei `.settings/language.settings.xml` sollte ignoriert werden (siehe README.md), weil sie automatisch generiert wird. Änderungen hier gehören nicht mit in den Commit.

2019-06-16 17:53 UTC, tsandmann approved these changes
Gut okay, wäre ganz gut das noch als Kommentar mit ins Makefile zu schreiben, damit es richtig verstanden wird. Insbesondere, weil das auch nur für den atmega1284p so passt.

Noch schöner wäre eigentlich für das Schreiben der Fuse-Bits extra Make-Targets zu machen, einmal mit und einmal ohne Bootloader-Modus.

2019-06-16 17:59 UTC, merged

2019-06-16 18:26 UTC, Nightwalker-87 commented
Ja, das könnte man durchaus so oder so ähnlich vorsehen, bzw. dann auch für den atmega 644(p) kompatibel machen. Wenn ich hierfür mal Zeit finde würde ich mich damit nochmal auseinandersetzen.